version: '3.7'
services:
  min-io-service:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - C:/Kek/distr/docker/volumes/storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /minio-image/storage --console-address :9001